name: 打包 React 项目
on: push

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    name: 构建与部署
    runs-on: ubuntu-latest
    
    steps:
      - name: 检查仓库 📦
        uses: actions/checkout@v4

      - name: 安装依赖
        run: |
          npm install --no-audit --no-fund
          npm run build
      
      - name: 部署到 GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build